Extra Linux cross-compilation targets
epics-base/ci-scripts pull request #69
Opened 2022-05-10 17:30 UTC by minijackson

As a Draft PR to see if it's going in the right direction, and because I can't seem to run GitHub actions on my fork?

2022-05-10 17:31 UTC, minijackson commented
Removing the draft status since the github actions don't seem to run on draft PRs

2022-05-10 18:06 UTC, minijackson commented
@mdavidsaver This is what I intended to do, but it seems that GHA didn't trigger in my fork (e.g: commit [0bcb170](https://github.com/minijackson/ci-scripts/commit/0bcb170f9103e5a69342edabcc4fee2a2360b90e)). I'm quite new to GHA actions, so I'm not sure what's wrong.

2022-05-12 16:43 UTC, minijackson commented
I will make a PR changing the epics-base ci workflow if and once this PR is merged.

2022-07-04 10:28 UTC, ralphlange commented on .github/workflows/build-and-test.yml
> -        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, windows-2019, windows-2016, macos-10.15]
windows-2016 is actually still supported on GitHub Actions.

2022-07-04 12:27 UTC, ralphlange commented
@mdavidsaver: Please also have a look at this - looks like a reasonable approach to me.

2022-07-05 17:48 UTC, mdavidsaver requested changes
Testing this PR on https://github.com/mdavidsaver/epics-base with no changes to my configuration gives errors on most jobs.  eg.

https://github.com/mdavidsaver/epics-base/runs/7201281364?check_suite_focus=true#step:5:46

```
Configuring EPICS build system
  EPICS Base build system set up for optimized build with shared (DLL) linking
  WARNING: deprecated WINE environment variable was specified, please use CI_CROSS_TARGETS
  Traceback (most recent call last):
    File ".ci/cue.py", line 1408, in <module>
      main(sys.argv[1:])
    File ".ci/cue.py", line 1404, in main
      args.func(args)
    File ".ci/cue.py", line 1126, in prepare
      prepare_cross_compilation(cross_target_info)
    File ".ci/cue.py", line 856, in prepare_cross_compilation
      raise ValueError(
  ValueError: Unknown CI_CROSS_TARGETS WINE. Please see the ci-scripts README for available values.
```

With similar errors for the RTEMS builds.

A couple of thoughts.

* `handle_old_cross_variables()` should log `$CI_CROSS_TARGETS` after editing.
* `handle_old_cross_variables()` could give a better suggestion.  eg. `Replace RTEMS=X with CI_CROSS_TARGETS=Y`.
* If we're going to continue to support the old `$RTEMS` and `$WINE`, then they should be covered by the test matrix.
* Should we bother supporting `$RTEMS` and `$WINE`, or force a migration now?

2022-07-05 17:48 UTC, mdavidsaver commented on README.md
> +- set the environment variable `LINUX_CROSS_arm=arm-linux-gnueabihf`
It would be helpful to have a list of supported/tested possibilities here, as well as in `.github/workflows/build-and-test.yml`.

2022-07-22 12:58 UTC, closed without merging